#version 460
#extension GL_ARB_shading_language_include : require

#include "common_defs.h"

//------------------------------------------------------------------------

layout (
    local_size_x = WORK_GROUP_LOCAL_SIZE_X,
    local_size_y = WORK_GROUP_LOCAL_SIZE_Y,
    local_size_y = WORK_GROUP_LOCAL_SIZE_Z
) in;

//------------------------------------------------------------------------
// Inputs.

layout (binding = MESH_BINDING, std140) uniform MeshBuffer {
    Mesh b_mesh[MAX_DRAWS];
};

//------------------------------------------------------------------------
// Outputs.

layout (binding = MODEL_BINDING, std140) writeonly buffer ModelBuffer {
    mat3x4 MT[];
} b_model;

layout (binding = TEXTURE_BINDING, std140) uniform TextureBuffer {
    MeshTextures b_tex[MAX_DRAWS];
};

layout (binding = INDIRECT_BINDING, std430) writeonly buffer DrawIndirectBuffer {
    DrawElementsIndirectCommand b_cmd[];
};

layout (binding = ATOMIC_COUNTER_BINDING) uniform atomic_uint drawCount;

//------------------------------------------------------------------------

void appendDraw(DrawElementsIndirectCommand cmd)
{
    uint idx = atomicCounterIncrement(drawCount);
    b_cmd[idx] = cmd;
}

//------------------------------------------------------------------------

void main()
{

}

//------------------------------------------------------------------------