#version 460
#extension GL_ARB_shading_language_include : require

#include "common_defs.h"

//------------------------------------------------------------------------

layout (
    local_size_x = WORK_GROUP_LOCAL_SIZE_X,
    local_size_y = WORK_GROUP_LOCAL_SIZE_Y,
    local_size_y = WORK_GROUP_LOCAL_SIZE_Z
) in;

//------------------------------------------------------------------------

struct DrawElementsIndirectCommand
{
    uint count;
    uint instanceCount;
    uint firstIndex;
    uint baseIndex;
    uint baseInstance;
};

//------------------------------------------------------------------------

layout (binding = INDIRECT_BINDING, std430) {
    DrawElementsIndirectCommand cmds[];
};

layout (binding = ATOMIC_COUNTER_BINDING) uniform atomic_uint drawCount;

//------------------------------------------------------------------------

void appendDraw(DrawElementsIndirectCommand cmd)
{
    uint idx = atomicCounterIncrement(drawCount);
    cmds[idx] = cmd;
}

//------------------------------------------------------------------------

void main()
{

}

//------------------------------------------------------------------------